name: Windows C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: gcc 3_Implementation/main.c -o main.exe
    - name: Run
      run: .\3_Implementation/main.exe
